[package]
name = "bgpexplorer"
version = "0.1.2"
authors = ["Vladimir Melnikov <wlad.w.m@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wladwm/bgpexplorer"
keywords = ["BGP","monitoring"]
categories = ["network-programming","web-programming"]
description = "This is a BGP route explorer for routing information database with ability to drill-down routes change history"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zettabgp = { version = "0.1.4", features = ["serde"] }
tokio = { version = "1.5.0", features = ["full"] }
tokio-util = "0.6.6"
hyper = { version = "0.14.5", features = ["full"] }
futures = "0.3.14"
futures-util = "0.3.14"
chrono = "0.4.19"
ini = { version = "1.3.0"}
async-trait = "0.1.49"
html-escape = "0.2.9"
serde = "1.0.125"
serde_json = "1.0.64"
lazy_static = "1.4.0"
regex = "1.4.6"
url = "2.2.1"
sled = "0.34.6"
dnssector = { version="0.2.4" }
whois-rust =  { version = "1.3.1", features= ["tokio"]  }


